### PR TITLE
feat: added bot count to getinfo

### PR DESCRIPTION
**Pull request by JariKCoding**
Resolves issue #151
Seems like @Brentdevent already implemented the count but didn't enable it in getinfo.

### CODE REVIEW

**Comment by Brentdevent** [comment]
It gave me some issues: https://github.com/momo5502/boiii/pull/187#issuecomment-1435167155
That's the reason I did not enable it.

**Comment by JariKCoding** [comment]
@Brentdevent Were you able to reliably reproduce it? It works fine for me and I'm not getting that error.

**Comment by Brentdevent** [comment]
Hmm weird enough neither do I anymore. I'm pretty sure I double checked it. Very strange 😅 
Anyway the error I was getting seems related to the stats hook anyway, So maybe it was something else. 🤔

**Review by momo5502 — APPROVED** [review]
I guess we'll see if it causes any bugs :D

**Pull request merged**
