### PR TITLE
Enable Dark matter camo.

### PR DESCRIPTION
**Pull request by joseupp**
Allows unlocking of the dark matter camo for the new stats menu

### CODE REVIEW

**Comment by JariKCoding** [comment]
Can you add some comments about what exactly you've changed? Seems like a mess with all the decompiled code.

**Comment by joseupp** [comment]
Only This has been removed.
Captura de pantalla 2023-03-15 233018
Captura de pantalla 2023-03-15 233118

**Comment by momo5502** [comment]
For the future, i suggest creating two commits. One with the untouched basefile you used and then a second commit with the changes only. that way it's simple to diff these two commits.
Optionally create a third commit inbetween with formatting.

**Comment by joseupp** [comment]
> Para el futuro, sugiero crear dos commits. Uno con el archivo base intacto que utilizó y luego una segunda confirmación solo con los cambios. De esa manera, es fácil diferenciar estos dos compromisos. Opcionalmente, cree una tercera confirmación intermedia con formato.

ok

**Comment by joseupp** [comment]
https://github.com/momo5502/boiii/pull/349

**Pull request closed without merging**
